import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile,readFile,readdir,symlink,stat} from 'node:fs/promises';
import {GameIO,LocalGameFiles,LocalGameHost} from '../src/local-game/host.mjs';
import {LocalGameSession} from '../src/local-game/session.mjs';
import {validateProfile} from '../src/local-game/profile.mjs';
import {repoRoot} from '../src/lifecycle/files.mjs';
import {digest} from '../src/lifecycle/cloud.mjs';
class Cloud {
 constructor(bytes=Buffer.from('canonical')){this.bytes=bytes;this.revision=bytes?1:0;this.session=null;this.acquireCount=0;this.commits=0;this.availability='free';this.worldId='synthetic';}
 async status(){return {worldId:this.worldId,currentRevision:this.revision,availability:this.availability,session:this.session,latest:this.bytes?{worldRevision:this.revision,sha256:digest(this.bytes),bytes:this.bytes.length,committedBy:{sessionId:this.committedBy}}:null};}
 async acquire(){assert.equal(this.availability,'free');this.acquireCount++;this.session={acquired:true,sessionId:randomUUID(),baseRevision:this.revision,baseSha256:this.bytes?digest(this.bytes):null,status:'hosting'};this.availability='busy';return {...this.session};}
 async heartbeat(id){assert.equal(id,this.session.sessionId);return {heartbeat:true,sessionId:id,lastHeartbeatUtc:new Date().toISOString()};}
 async download(){return this.corrupt?Buffer.from('bad'):this.bytes;}
 async commit(s,b){this.commits++;if(this.fail)throw Error('UPLOAD_FAILED');assert.equal(s.sessionId,this.session.sessionId);this.bytes=b;this.revision++;this.committedBy=s.sessionId;this.session=null;this.availability='free';if(this.lostResponse)throw Error('RESPONSE_LOST');}
}
function memory(cloud=new Cloud()){
 const files={value:Buffer.from('local'),backups:[],records:[],locked:false,installs:0,stages:new Map(),
 async lock(){this.locked=true;},async unlock(){this.locked=false;},async previous(){return null;},async record(s){this.records.push(structuredClone(s));},async stage(b){const p=randomUUID();this.stages.set(p,b);return p;},async readStage(p){return this.stages.get(p);},
 async install(p,e){this.backups.push(this.value);this.value=this.stages.get(p);this.installs++;return {sha256:digest(this.value),bytes:this.value.length};},
 async snapshot(){this.backups.push(this.value);return {path:await this.stage(this.value),sha256:digest(this.value),bytes:this.value.length};},
 async stable(){this.stabilized=true;return {sha256:digest(this.value),bytes:this.value.length};}};
 const server={running:false,autoLaunch:false,active(){return this.running;},async inspect(){return {active:this.running};},async assertStopped(){if(this.running)throw Error('WS_GAME_ACTIVE');},async start(){this.launched=true;},async stop(){throw Error('MUST_NOT_STOP_GAME');}};
 const s=new LocalGameSession({files,server,cloud});s.beginHeartbeats=()=>{};return {s,files,server,cloud};
}
async function cycle(m){await m.s.play();await m.s.tick();assert.equal(m.s.state.phase,'waiting_for_game');m.server.running=true;await m.s.tick();assert.equal(m.s.state.phase,'running');m.files.value=Buffer.from('synthetic progress');m.server.running=false;await m.s.tick();}
test('busy cloud never installs, snapshots or locks local save',async()=>{const m=memory();m.cloud.availability='busy';await assert.rejects(m.s.play(),/WORLD_BUSY/);assert.equal(m.files.locked,false);assert.equal(m.files.backups.length,0);assert.equal(m.files.installs,0);});
test('bad download hash aborts before import',async()=>{const m=memory();m.cloud.corrupt=true;await assert.rejects(m.s.play(),/DOWNLOAD_INTEGRITY_FAILED/);assert.equal(m.files.installs,0);assert.equal(m.s.state.phase,'recovery_required');});
test('active client blocks assume without acquiring',async()=>{const m=memory();m.server.running=true;await assert.rejects(m.s.play(),/WS_GAME_ACTIVE/);assert.equal(m.cloud.acquireCount,0);});
test('full session observes game exit, stabilizes, snapshots, commits and releases',async()=>{const m=memory();await cycle(m);assert.equal(m.files.stabilized,true);assert.equal(m.cloud.revision,2);assert.equal(m.cloud.session,null);assert.equal(m.files.locked,false);assert.equal(m.s.state.phase,'completed');assert.ok(m.files.records.some(r=>r.phase==='finalizing'));});
test('running game can heartbeat but cannot publish',async()=>{const m=memory();await m.s.play();m.server.running=true;await m.s.tick();await assert.rejects(m.s.publish(),/WS_GAME_ACTIVE/);await m.s.tick();assert.equal(m.cloud.commits,0);assert.equal(m.s.state.phase,'running');});
test('upload failure preserves original session and journal',async()=>{const m=memory();m.cloud.fail=true;await assert.rejects(cycle(m),/COMMIT_UNCONFIRMED/);assert.equal(m.cloud.revision,1);assert.equal(m.s.state.phase,'recovery_required');assert.equal(m.s.state.session.sessionId,m.cloud.session.sessionId);assert.equal(m.files.locked,true);assert.equal(m.files.value.toString(),'synthetic progress');});
test('lost commit response reconciles without duplicate upload',async()=>{const m=memory();m.cloud.lostResponse=true;await cycle(m);assert.equal(m.cloud.commits,1);assert.equal(m.s.state.phase,'completed');});
test('stale session cannot be stolen or revived automatically',async()=>{const m=memory();await m.s.play();m.cloud.availability='recovery_required';await assert.rejects(m.s.pulse(),/RECOVERY_REQUIRED/);assert.equal(m.cloud.acquireCount,1);await m.s.recover(Error('RECOVERY_REQUIRED'));assert.equal(m.s.state.phase,'recovery_required');});
test('loss of session never kills game',async()=>{const m=memory();await m.s.play();m.server.running=true;m.cloud.session=null;await assert.rejects(m.s.pulse(),/SESSION_LOST/);await m.s.recover(Error('SESSION_LOST'));assert.equal(m.server.running,true);assert.equal(m.cloud.commits,0);});
test('adoption requires explicit confirmation and closed game',async()=>{const m=memory(new Cloud(null));await assert.rejects(m.s.adopt(),/CONFIRMATION/);m.server.running=true;await assert.rejects(m.s.adopt({confirmed:true,expectedHash:digest(m.files.value)}),/WS_GAME_ACTIVE/);assert.equal(m.cloud.acquireCount,0);});
test('adoption cannot replace an existing canonical world',async()=>{const m=memory();await assert.rejects(m.s.adopt({confirmed:true,expectedHash:digest(m.files.value)}),/WORLD_ALREADY_EXISTS/);assert.equal(m.cloud.revision,1);assert.equal(m.files.backups.length,0);});
test('new world adoption revision one does not affect old world',async()=>{const old=new Cloud(Buffer.from('old independent world'));old.worldId='worldsynctest';const before=await old.status();const m=memory(new Cloud(null));m.cloud.worldId='posto-da-mata';await m.s.adopt({confirmed:true,expectedHash:digest(m.files.value)});assert.equal(m.cloud.revision,1);assert.equal(m.cloud.session,null);assert.deepEqual(await old.status(),before);});
test('changed adoption file cannot acquire or publish',async()=>{const m=memory(new Cloud(null));await assert.rejects(m.s.adopt({confirmed:true,expectedHash:'a'.repeat(64)}),/ADOPTION_FILE_CHANGED/);assert.equal(m.cloud.commits,0);assert.equal(m.cloud.acquireCount,0);});
test('legacy world ID rejected in local-game profiles',()=>{assert.throws(()=>validateProfile({mode:'local-game',profile:'test',worldId:'worldsynctest'}));});
async function fixture(){const root=path.join(repoRoot,'tests/.scratch/local-game',randomUUID());const saveRoot=path.join(root,'saves');const state=path.join(root,'state');for(const p of [saveRoot,path.join(state,'staging'),path.join(state,'backups')])await mkdir(p,{recursive:true});const profile={profile:'fixture-'+randomUUID(),saveRoot,fileName:'opaque-001.sav'};const io=new GameIO(profile,{fixtureRoot:saveRoot});const files=new LocalGameFiles(state,profile,io);await writeFile(files.save,'local synthetic');await writeFile(path.join(saveRoot,'other-world.sav'),'untouched');return {root,profile,io,files};}
test('real filesystem fixture: backup, selected-only replacement and recoverable snapshot',async()=>{const {files,profile}=await fixture();const bytes=Buffer.from('new canonical');const p=await files.stage(bytes);const result=await files.install(p,{sha256:digest(bytes),bytes:bytes.length});assert.equal((await readFile(result.backup)).toString(),'local synthetic');assert.equal((await readFile(files.save)).toString(),'new canonical');assert.equal((await readFile(path.join(profile.saveRoot,'other-world.sav'))).toString(),'untouched');const s=await files.snapshot();assert.equal(s.sha256,digest(bytes));assert.equal((await readFile(s.backup)).toString(),'new canonical');files.requiredFinal={sha256:'a'.repeat(64),bytes:bytes.length};await assert.rejects(files.snapshot(),/UNCONFIRMED_SAVE_CHANGE/);});
test('real process guards use exact client names; active game blocks discover/install/snapshot',async()=>{const {files,io}=await fixture();io.processNames=['Steam','RSDragonwildsServer','unrelatedDragonwilds'];assert.equal((await io.call('Inspect')).active,false);const p=await files.stage(Buffer.from('stage'));for(const name of ['RSDragonwilds','RSDragonwilds-Win64-Shipping','RSDragonwilds-WinGDK-Shipping']){io.processNames=[name];assert.equal((await io.call('Inspect')).active,true);await assert.rejects(files.install(p,{sha256:digest(Buffer.from('stage')),bytes:5}),/WS_GAME_ACTIVE/);await assert.rejects(files.snapshot(),/WS_GAME_ACTIVE/);await assert.rejects(io.call('Discover'),/WS_GAME_ACTIVE/);}assert.equal((await readFile(files.save)).toString(),'local synthetic');});
test('defensive discovery separates filename from display identity',async()=>{const {io}=await fixture();const d=await io.call('Discover');assert.equal(d.worlds.length,2);assert.equal(d.worlds[0].identity,'filename_hint_only');assert.ok(d.worlds.every(w=>w.sha256.length===64));});
test('unexpected root, traversal, junction and corrupt staging are rejected',async()=>{const {io,files,root,profile}=await fixture();await assert.rejects(io.call('Metadata',{SaveRoot:root}),/WS_SAVE_ROOT_REJECTED/);await assert.rejects(io.call('Metadata',{FileName:'../escape.sav'}),/WS_SAVE_NAME_REJECTED/);const linked=path.join(root,'linked');await symlink(profile.saveRoot,linked,'junction');await assert.rejects(new GameIO({...profile,saveRoot:linked},{fixtureRoot:linked}).call('Metadata'),/WS_LINK_REJECTED/);const p=await files.stage(Buffer.from('bad'));await assert.rejects(files.install(p,{sha256:'a'.repeat(64),bytes:3}),/WS_IMPORT_INTEGRITY_FAILED/);assert.equal((await readdir(path.join(files.root,'backups'))).length,0);});
test('stability waits for matching hash size mtime and rejects restarted game',async()=>{let calls=0;const io={async call(){calls++;return {sha256:calls<3?'a':'b',bytes:1,mtimeUtc:'fixture'};},async assertStopped(){}};const f=new LocalGameFiles('unused', {saveRoot:'unused',fileName:'test.sav'},io);await f.stable(async()=>{}, {quietMs:60,intervalMs:10,timeoutMs:500});assert.ok(calls>=4);io.assertStopped=async()=>{throw Error('WS_GAME_ACTIVE');};await assert.rejects(f.stable(async()=>{}, {quietMs:1,intervalMs:2,timeoutMs:100}),/WS_GAME_ACTIVE/);});
test('filesystem E2E: canonical install -> observed game -> changed fixture -> verified commit',async()=>{
 const {files,io}=await fixture();const cloud=new Cloud();const server=new LocalGameHost(io,{autoLaunch:false});const s=new LocalGameSession({files,server,cloud});s.beginHeartbeats=()=>{};
 const stable=files.stable.bind(files);files.stable=p=>stable(p,{quietMs:50,intervalMs:10,timeoutMs:10000});
 await s.play();assert.equal((await readFile(files.save)).toString(),'canonical');
 io.processNames=['RSDragonwilds-Win64-Shipping'];await s.tick();assert.equal(s.state.phase,'running');await assert.rejects(s.publish(),/WS_GAME_ACTIVE/);
 // Fixture simulates game output; it is not a real game process or save.
 await writeFile(files.save,'fixture final progress');io.processNames=[];await s.tick();
 assert.equal(s.state.phase,'completed');assert.equal(cloud.revision,2);assert.equal(digest(cloud.bytes),digest(Buffer.from('fixture final progress')));assert.equal(cloud.session,null);
 assert.ok((await readdir(files.root)).some(n=>n.endsWith('.closed')));assert.ok((await readdir(path.join(files.root,'backups'))).length>=3);
});
test('same target cannot be controlled by a second profile',async()=>{
 const {files,profile,io}=await fixture();await files.lock();const other=new LocalGameFiles(files.root,{...profile,profile:'other-profile'},io);
 await assert.rejects(other.lock(),/LOCAL_RECOVERY_REQUIRED/);await files.unlock();
});
