import test from 'node:test';import assert from 'node:assert/strict';
import path from 'node:path';import {randomUUID} from 'node:crypto';
import {mkdir,writeFile,readFile,readdir,access,symlink} from 'node:fs/promises';
import {spawn} from 'node:child_process';import {createInterface} from 'node:readline';import {createServer} from 'node:http';
import {repoRoot} from '../src/lifecycle/files.mjs';import {userDataPaths} from '../src/user-data/paths.mjs';import {initializeUserData} from '../src/user-data/migrate.mjs';
async function fixture(){const base=path.join(repoRoot,'tests/.scratch/user-data',randomUUID());const core=path.join(base,'version-A/core');const paths=userDataPaths(path.join(base,'AppData'));await mkdir(path.join(core,'config/local-game'),{recursive:true});const profile={mode:'local-game',profile:'pc-a',worldId:'posto-da-mata',displayName:'Posto da Mata',saveRoot:path.join(base,'NEVER_OPEN_GAME_SAVES'),fileName:'opaque.sav',autoLaunch:true,host:'WILLI',machineId:randomUUID(),cloudUrl:'https://example.com'};await writeFile(path.join(core,'config/local-game/pc-a.local.json'),JSON.stringify(profile));return {base,core,paths,profile};}
test('user root and subdirectories are independent from executable folder',()=>{const p=userDataPaths('C:\\Synthetic\\AppData\\Local');assert.equal(p.root,'C:\\Synthetic\\AppData\\Local\\WorldSync');assert.equal(p.profiles,path.join(p.root,'profiles'));assert.equal(p.backups,path.join(p.root,'backups'));});
test('migration preserves profiles, last selection, completed journal, backup and original bytes',async()=>{const f=await fixture();const old=path.join(f.core,'state/local-game/pc-a');await mkdir(path.join(old,'backups'),{recursive:true});await writeFile(path.join(old,'lifecycle.json'),JSON.stringify({phase:'completed',session:null,publishedRevision:1}));await writeFile(path.join(old,'backups/fixture.sav'),'SYNTHETIC_INTERNAL_BACKUP');await mkdir(path.join(f.core,'ui/artifacts'),{recursive:true});await writeFile(path.join(f.core,'ui/artifacts/last-profile.txt'),'pc-a');const result=await initializeUserData(f);assert.equal(result.migrated,true);assert.deepEqual(JSON.parse(await readFile(path.join(f.paths.profiles,'pc-a.local.json'))),f.profile);assert.equal(await readFile(path.join(f.paths.preferences,'last-profile.txt'),'utf8'),'pc-a');assert.equal(await readFile(path.join(f.paths.backups,'pc-a/fixture.sav'),'utf8'),'SYNTHETIC_INTERNAL_BACKUP');assert.equal(await readFile(path.join(old,'backups/fixture.sav'),'utf8'),'SYNTHETIC_INTERNAL_BACKUP');await assert.rejects(access(f.profile.saveRoot));assert.ok(!JSON.stringify(result).includes('token'));const second=await initializeUserData({...f,core:path.join(f.base,'version-B/core')});assert.equal(second.existing,true);});
for(const phase of ['running','recovery_required','acquiring','publishing',null])test('migration refuses unsafe journal '+phase,async()=>{const f=await fixture();const old=path.join(f.core,'state/local-game/pc-a');await mkdir(old,{recursive:true});await writeFile(path.join(old,'lifecycle.json'),JSON.stringify({phase,session:null}));await assert.rejects(initializeUserData(f),/MIGRATION_SESSION_PENDING/);await assert.rejects(access(f.paths.root));await access(path.join(old,'lifecycle.json'));});
test('migration refuses target lock and keeps source untouched',async()=>{const f=await fixture();const old=path.join(f.core,'state/local-game/target-locks');await mkdir(old,{recursive:true});await writeFile(path.join(old,'target.lock'),'synthetic');await assert.rejects(initializeUserData(f),/MIGRATION_SESSION_PENDING/);await access(path.join(old,'target.lock'));});
test('migration refuses links, invalid profile and secret fields',async()=>{for(const kind of ['invalid','secret','link']){const f=await fixture();const p=path.join(f.core,'config/local-game/pc-a.local.json');if(kind==='invalid')await writeFile(p,'{}');if(kind==='secret')await writeFile(p,JSON.stringify({...f.profile,token:'SYNTHETIC_ONLY'}));if(kind==='link')await symlink(f.base,path.join(f.core,'state'),'junction');await assert.rejects(initializeUserData(f));await assert.rejects(access(f.paths.root));}});
test('version B finds legacy version A next to it and does not overwrite established destination',async()=>{const f=await fixture();const b=path.join(f.base,'version-B/core');await mkdir(b,{recursive:true});await initializeUserData({...f,core:b});await writeFile(path.join(f.paths.profiles,'pc-a.local.json'),JSON.stringify({...f.profile,host:'NEW'}));await initializeUserData({...f,core:b});assert.equal(JSON.parse(await readFile(path.join(f.paths.profiles,'pc-a.local.json'))).host,'NEW');assert.equal(JSON.parse(await readFile(path.join(f.core,'config/local-game/pc-a.local.json'))).host,'WILLI');});
test('ambiguous installations fail closed',async()=>{const f=await fixture();await assert.rejects(initializeUserData({...f,sources:[f.core,f.core]}),/MIGRATION_MULTIPLE_SOURCES/);});
test('two app locations reuse data; startup status is immediate and pending until mock response',async()=>{
 const f=await fixture();await initializeUserData(f);let requested;const requestSeen=new Promise(r=>requested=r);
 const server=createServer((req,res)=>{requested(Date.now());setTimeout(()=>{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({worldId:'posto-da-mata',currentRevision:1,availability:'free',session:null,latest:{worldRevision:1,sha256:'a'.repeat(64),bytes:10,committedBy:{host:'WILLI'},committedAtUtc:'2026-09-27T06:29:00Z'}}));},1200);});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));await writeFile(path.join(f.paths.profiles,'pc-a.local.json'),JSON.stringify({...f.profile,cloudUrl:'http://127.0.0.1:'+server.address().port}));await writeFile(path.join(f.paths.profiles,'invalid.local.json'),'{}');
 const child=spawn(process.execPath,[path.join(repoRoot,'ui/bridge.mjs')],{cwd:f.base,windowsHide:true,env:{...process.env,LOCALAPPDATA:path.dirname(f.paths.root),WORLDSYNC_API_TOKEN:'SYNTHETIC_TEST_TOKEN_0123456789'},stdio:['pipe','pipe','pipe']});child.stderr.on('data',()=>{});const messages=[];let selectTime=0;
 const done=new Promise((resolve,reject)=>{child.on('error',reject);createInterface({input:child.stdout}).on('line',line=>{try{const m=JSON.parse(line);messages.push(m);if(m.type==='profiles'){assert.deepEqual(m.names,['pc-a']);assert.equal(m.userDataRoot,f.paths.root);selectTime=Date.now();child.stdin.write(JSON.stringify({action:'select',profile:'pc-a'})+'\n');}if(m.type==='state'&&m.cloud){assert.equal(m.cloud.latest.host,'WILLI');child.stdin.write('{"action":"quit"}\n');}if(m.type==='closed')resolve();}catch(e){reject(e);}});});
 try{const time=await requestSeen;assert.ok(time-selectTime<5000);await done;assert.ok(messages.some(m=>m.type==='consulting'));assert.ok(messages.some(m=>m.type==='state'&&m.consulting&&!m.cloud));assert.ok(!JSON.stringify(messages).includes('SYNTHETIC_TEST_TOKEN'));}finally{child.stdin.end();server.close();}
});
test('incomplete state without journal blocks migration',async()=>{const f=await fixture();const dir=path.join(f.core,'state/local-game/pc-a/staging');await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'fixture.sav'),'SYNTHETIC');await assert.rejects(initializeUserData(f),/MIGRATION_SESSION_PENDING/);});
test('LocalGameFiles writes internal state/locks/backups under shared synthetic UserDataRoot',async()=>{
 const f=await fixture();const previous=process.env.LOCALAPPDATA;process.env.LOCALAPPDATA=path.dirname(f.paths.root);
 try{
  const {GameIO,LocalGameFiles}=await import('../src/local-game/host.mjs');
  const saveRoot=path.join(repoRoot,'tests/.scratch/local-game',randomUUID(),'saves');await mkdir(saveRoot,{recursive:true});await writeFile(path.join(saveRoot,'fixture.sav'),'SYNTHETIC');
  const profile={...f.profile,saveRoot,fileName:'fixture.sav'};const io=new GameIO(profile,{fixtureRoot:saveRoot});const files=await LocalGameFiles.create(profile,io);
  await files.lock();const snapshot=await files.snapshot();assert.ok(snapshot.backup.startsWith(f.paths.backups+path.sep));assert.ok(snapshot.path.startsWith(f.paths.state+path.sep));await files.unlock();
  assert.equal(await readFile(snapshot.backup,'utf8'),'SYNTHETIC');
 }finally{if(previous===undefined)delete process.env.LOCALAPPDATA;else process.env.LOCALAPPDATA=previous;}
});
